JKISM 2024
JKISoftware/JKI-State-Machine pull request #31
Opened 2024-07-04 12:59 UTC by Tom-McQuillan

## New Features and Bug Fixes
- #21 New Support VI -> "Select State(s)" allows conditional (Boolean or error) enqueuing of states
- #11 JKI SM Template  -> Error Handler is now appends the  previous state string (and raw arguments+comments) to the error message
- #30 JKI SM Template  -> Added UI: Cleanup state (called by Macro: Exit)
- #29 JKI SM Template ->  Clears warnings in the Idle state
- #17 JKI SM Template ->  fixed typo in UI: Initialize state comment

## Developer Fixes
- Updated VIPC file to include all package dependencies required to open the source and build VIs

2024-07-05 15:28 UTC, jimkring requested changes
@Tom-McQuillan

Can you update the icons to look like the following?

![image](https://github.com/JKISoftware/JKI-State-Machine/assets/381432/4893d77e-9145-46ff-9064-abba581282a0)

2024-07-05 15:28 UTC, jimkring commented on source/State Machine Support API/Clear Warning.vi
One way to simplify things would be to move the clearing of warnings into `Parse State Queue.vi`

![image](https://github.com/JKISoftware/JKI-State-Machine/assets/381432/99663b14-3bb0-41e0-8b8c-36c9c1b50575)

I'm curious what @philippe-guerit would think about this idea.

2024-07-05 15:28 UTC, jimkring commented on source/State Machine Support API/Clear Warning.vi
Clear Warning should probably be set to Subroutine Priority, since Parse State Queue (and others probably) are set to that priority.

![image](https://github.com/JKISoftware/JKI-State-Machine/assets/381432/89320aa3-df6f-4287-b1af-308114bd3509)

Note: We should add a Caraya test that verifies Execution settings (reentrancy, subroutine, etc.) by putting the VI Under Test in a static refnum and reading a property node to assert the correct settings.
- [x] Add Caraya test to verify execution settings of utility VIs

2024-07-05 15:28 UTC, jimkring commented on source/State Machine Support API/Clear Warning.vi
It might make sense to change to a smaller conpane pattern
![image](https://github.com/JKISoftware/JKI-State-Machine/assets/381432/4b1a0fbe-cb27-454f-8be8-f51bf2f72225)

2024-07-05 15:28 UTC, jimkring commented on source/State Machine Support API/Clear Warning.vi
Probably want to comment the code (and wire the error into the select terminal)

> To clear "warnings" (i.e. when status is False, but code and source have values), we need to ensure that code and source are forced to defaults when there is no error.

![image](https://github.com/JKISoftware/JKI-State-Machine/assets/381432/0cf35f8f-7c12-423b-b4e0-b7fb1f5b2215)

2024-07-05 15:28 UTC, jimkring commented on source/State Machine Support API/Clear Warning.vi
error in should probably be a required input
![image](https://github.com/JKISoftware/JKI-State-Machine/assets/381432/9a201554-ec6b-4d6d-8c6a-2bac3498d736)

2024-07-05 15:28 UTC, jimkring commented on source/State Machine Support API/Conditional State String.vi
The various support VIs use gray/black blocks for the queue elements and green triangles for arrows.
- gray block signifies not yet queued
- black block signifies queued 

Would it make sense to update Conditional State String and Periodic State String to use consistent iconography? For example...

![image](https://github.com/JKISoftware/JKI-State-Machine/assets/381432/acc68154-5533-44c1-8a72-9181cb122a86)

2024-07-05 15:28 UTC, jimkring commented on source/State Machine Support API/Conditional State String.vi
@Tom-McQuillan and I (@jimkring) reviewed icons and thought these (below) were more consistent with the visual language already being used.

![image](https://github.com/JKISoftware/JKI-State-Machine/assets/381432/a3e6b0d2-c509-4f84-98e6-ab1f61331a3e)

2024-07-05 15:29 UTC, jimkring requested changes
@Tom-McQuillan let's remove the Clear Warnings utility VI

2024-07-10 16:49 UTC, jimkring commented on source/State Machine Templates/String-Based Queued State Machine (Basic 1.0).vi
>  [616a596](https://github.com/JKISoftware/JKI-State-Machine/commit/616a596e298517a8ea3783dcccf51addc025ed88) Saved JKI SM Template with Idle, Timeout case visible

@Tom-McQuillan we could probably create a unit test to verify that the JKI SM Template has the `Idle, Timeout` case visible.

2024-07-10 17:23 UTC, Tom-McQuillan commented on source/State Machine Templates/String-Based Queued State Machine (Basic 1.0).vi
Done
![image](https://github.com/JKISoftware/JKI-State-Machine/assets/104849466/d8bcbd10-4a5d-4f55-875c-005d7aacc293)

2024-07-10 17:45 UTC, Tom-McQuillan commented
> @Tom-McQuillan
> 
> Can you update the icons to look like the following?
> 
> ![image](https://private-user-images.githubusercontent.com/381432/346168904-4893d77e-9145-46ff-9064-abba581282a0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA2MzM4MjYsIm5iZiI6MTcyMDYzMzUyNiwicGF0aCI6Ii8zODE0MzIvMzQ2MTY4OTA0LTQ4OTNkNzdlLTkxNDUtNDZmZi05MDY0LWFiYmE1ODEyODJhMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxMFQxNzQ1MjZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hZDYzZDMyMGZjMjBlNWRhMDJmOWMwYTE4Y2I1Y2IxMGZjZGM1ZDE2Y2IzOWE5NWJhN2MyMjJkZmZmNjYyZWFhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.zbyt6wR0kyKAC6xSu4sU9tgyp-eXdRRM8tfzRGyGXS4)

Done

2024-07-10 17:46 UTC, Tom-McQuillan commented
> @Tom-McQuillan let's remove the Clear Warnings utility VI

Done

2024-07-10 17:47 UTC, Tom-McQuillan commented on source/State Machine Support API/Conditional State String.vi
Done

2024-08-06 16:13 UTC, jimkring commented on source/State Machine Support API/Clear Warning.vi
N/A, since this utility VI was removed

2024-08-06 16:14 UTC, jimkring commented on source/State Machine Support API/Clear Warning.vi
N/A

2024-08-08 10:32 UTC, Tom-McQuillan commented on source/State Machine Support API/Clear Warning.vi
This function is no longer used

2024-08-27 09:27 UTC, merged